/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface User {
  'id' : bigint,
  'referralCode' : string,
  'name' : string,
  'createdAt' : bigint,
  'ancestors' : Array<bigint>,
  'upiId' : string,
  'utrId' : [] | [string],
  'mobile' : string,
  'registrationStatus' : string,
  'referredByCode' : [] | [string],
  'walletBalance' : bigint,
}
export interface UserProfile { 'userId' : bigint, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'category' : string,
  'videoUrl' : string,
  'uploadedAt' : bigint,
}
export interface WalletTransaction {
  'id' : bigint,
  'userId' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : string,
  'userId' : bigint,
  'upiId' : string,
  'amount' : bigint,
  'requestedAt' : bigint,
  'resolvedAt' : [] | [bigint],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'confirmPayment' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'editVideo' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfirmedUserWalletDetails' : ActorMethod<
    [bigint],
    [bigint, Array<WalletTransaction>]
  >,
  'getPendingWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getProcessedWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getReceivedReferralEarnings' : ActorMethod<[bigint], [] | [bigint]>,
  'getUserById' : ActorMethod<[bigint], [] | [User]>,
  'getUserByReferralCode' : ActorMethod<[string], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideosByCategory' : ActorMethod<[string], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processWithdrawalRequest' : ActorMethod<[bigint, boolean], undefined>,
  'registerUser' : ActorMethod<[string, string, string, [] | [string]], string>,
  'removeUser' : ActorMethod<[bigint], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitUTR' : ActorMethod<[string, string, string], undefined>,
  'uploadVideo' : ActorMethod<[string, string, string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];