/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'referralCode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat,
  'ancestors' : IDL.Vec(IDL.Nat),
  'upiId' : IDL.Text,
  'utrId' : IDL.Opt(IDL.Text),
  'mobile' : IDL.Text,
  'registrationStatus' : IDL.Text,
  'referredByCode' : IDL.Opt(IDL.Text),
  'walletBalance' : IDL.Nat,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
  'uploadedAt' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Nat,
  'name' : IDL.Text,
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'userId' : IDL.Nat,
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
  'requestedAt' : IDL.Nat,
  'resolvedAt' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPayment' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'editVideo' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConfirmedUserWalletDetails' : IDL.Func(
      [IDL.Nat],
      [IDL.Nat, IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'getPendingWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getProcessedWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getReceivedReferralEarnings' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
  'getUserByReferralCode' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitUTR' : IDL.Func([IDL.Text], [], []),
  'uploadVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'referralCode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
    'ancestors' : IDL.Vec(IDL.Nat),
    'upiId' : IDL.Text,
    'utrId' : IDL.Opt(IDL.Text),
    'mobile' : IDL.Text,
    'registrationStatus' : IDL.Text,
    'referredByCode' : IDL.Opt(IDL.Text),
    'walletBalance' : IDL.Nat,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
    'uploadedAt' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'userId' : IDL.Nat, 'name' : IDL.Text });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'userId' : IDL.Nat,
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
    'requestedAt' : IDL.Nat,
    'resolvedAt' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPayment' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'editVideo' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConfirmedUserWalletDetails' : IDL.Func(
        [IDL.Nat],
        [IDL.Nat, IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'getPendingWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getProcessedWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getReceivedReferralEarnings' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
    'getUserByReferralCode' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processWithdrawalRequest' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitUTR' : IDL.Func([IDL.Text], [], []),
    'uploadVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };